export default {
    products: [
        {
            _id: '1',
            name: 'Headset',
            category: 'Acessórios',
            image: '/frontend/public/images/Headset.png',
            price: 149,
            brand: 'Samsung',
            rating: 4.3,
            numReviews: 10,
            countInStock: 3,
        },
        {
            _id: '2',
            name: 'Headset',
            category: 'Acessórios',
            image: '/frontend/public/images/Headset.png',
            price: 149,
            brand: 'Samsung',
            rating: 4.5,
            numReviews: 5,
            countInStock: 3,
        }, 
        {
            _id: '3',
            name: 'Headset',
            category: 'Acessórios',
            image: '/frontend/public/images/Headset.png',
            price: 149,
            brand: 'Samsung',
            rating: 4.1,
            numReviews: 8,
            countInStock: 3,
        },    
        {
            _id: '4',
            name: 'Headset',
            category: 'Acessórios',
            image: '/frontend/public/images/Headset.png',
            price: 149,
            brand: 'Samsung',
            rating: 4.2,
            numReviews: 10,
            countInStock: 3,
        },    
        {
            _id: '5',
            name: 'Headset',
            category: 'Acessórios',
            image: '/frontend/public/images/Headset.png',
            price: 149,
            brand: 'Samsung',
            rating: 4.5,
            numReviews: 9,
            countInStock: 3,
        },       
                ]
            }